### ISSUE TITLE
Strike-through doesn't work well with todo lists

### ISSUE THREAD

**Issue by f1ames** [ckeditor/github-writer#125]
Creating strikethrough text for the existing todo list item looks correct in the editor:

![Zrzut ekranu z 2020-03-31 14-46-17](https://user-images.githubusercontent.com/1061942/78028178-e38cd880-735e-11ea-9b98-bc3726bdcb18.png)

However after saving it is changed to:

![Zrzut ekranu z 2020-03-31 14-46-32](https://user-images.githubusercontent.com/1061942/78028218-f3a4b800-735e-11ea-9ecf-a4c6377e9a2e.png)

And the markdown for it looks like this:

![Zrzut ekranu z 2020-03-31 14-47-00](https://user-images.githubusercontent.com/1061942/78028245-fd2e2000-735e-11ea-9976-ccf6a38db34a.png)

You can add `[ ]` manually in the Markdown editor, but then when switching to RTE it is lost again (the message about unsupported markup is shown :+1:), which means in such situations you are stuck with the Markdown editor.

**Comment by mateuszzagorski** [comment]
Closing, as it does not seem to be replicable anymore after the upstream fix.
