### ISSUE TITLE
Can not move cursor before uploaded image

### ISSUE THREAD

**Issue by vokiel** [ckeditor/github-writer#127]
**TC**

1.  Upload image with D&D.
2.  Try to put the cursor before the image and start typing.

**Current**: There is no way to move the cursor before the image.  
**Expected**: It should be possible with `LEFT ARROW` or `HOME` / `CTRL + HOME`.

**Comment by jawn** [comment]
Does this also explain why you can't type before a table at the top of an editor?

**Comment by fredck** [comment]
> Does this also explain why you can't type before a table at the top of an editor?

Yes, that's the exact same reason. For now you can work this around with the solution I pointed out 3 comments above -> select table + <kbd>shift+enter</kbd>

**Comment by fredck** [comment]
I confirm that the definitive solution for this has been introduced with CKEditor 5 v19.1.0, recently introduced here with 2e0c4c9.
