### ISSUE TITLE
Can't convert list to a todolist if items are wrapped in a link

### ISSUE THREAD

**Issue by mlewand** [ckeditor/github-writer#129]
1.  Open an issue and focus the editor to create a new comment.
2.  Create an unordered link with 2 items (say "foo" and "bar")

![](https://user-images.githubusercontent.com/5353898/78244795-9d628100-74e6-11ea-9cc8-0b97b7011aef.png)

1.  `ctrl+a`
2.  make a link (`ctrl+k`)
3.  set some dummy url and commit the dialog
4.  click the "Add a task list" button to convert it into a todo list
5.  submit the comment

## Expected

Todo list is preserved (like it was visible in the editor)

## Actual

Unordered list is added

It looks to be gh-rte specific - I can't reproduce it on https://ckeditor.com/docs/ckeditor5/latest/features/todo-lists.html by checking `editor.getData()`.

**Comment by mateuszzagorski** [comment]
Upstream issue mentioned in #125 was resolved, and I am no longer able to replicate the issue.
