### ISSUE TITLE
A way to restore a lost content (autosave to local storage?)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#134]
I've just lost 20 minutes of work because I mistakenly clicked "Close issue" and GHRTE didn't save the comment (which GH normally does). Since it overrides how the form works, the "go back" browser option didn't help either.

Besides fixing the "Close issue" button, I'd love to see some way of restoring lost content. Some sort of autosave to the local storage and ways to get the content back from it would be an amazing improvement, also over what GH offers by default. The problem here is that normally you can install browser addons which save you from losing your content but with GHRTE it's gone. Therefore, GHRTE should offer something for that.

**Comment by stefaniefgray** [comment]
This issue is still happening

I accidentally clicked on my own profile page while previewing an issue I was in the process of creating, and just lost 30 minutes of work :/ 

Text has completely disappeared, back button did not restore. Have used Github since 2014. This is disappointing.

**Comment by snproj** [comment]
Just happened to me 🥲 afaik doesn't happen on Gitlab? When I refresh everything's still there.

Solution would be nice, since I enjoy typing longwinded markup essays on Github
