### ISSUE TITLE
Clicking "Comment" doesn't always save the comment

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#135]
I don't know if this is a one time thing, but I just had an problem with submitting a comment. First, I stumbled upon #134 and now this so perhaps something changed on GH side.

So, when clicking the "Comment" button nothing was happening and one error was being logged to the console:

```plaintext
An invalid form control with name='comment[body]' is not focusable.
```

![](https://user-images.githubusercontent.com/156149/78669242-455bbe00-78dc-11ea-99ca-59f988eafcdf.png)

I refreshed the page and now commenting works again. Curious to see if anyone stumbles upon this.

**Comment by MaximKurbanov** [comment]
f

**Comment by wangnanv5** [comment]
it‘s still not work
