### ISSUE TITLE
Autocomplete does not work in Firefox

### ISSUE THREAD

**Issue by warpech** [ckeditor/github-writer#167]
When I'm typing `#`, the regular GitHub editor shows an autocomplete. CKSource GitHub Writer does not show anything, though for a short while what I'm typing highlights in blue.

Expected (GitHub editor):

![diff](https://user-images.githubusercontent.com/566463/81179858-88c44d80-8faa-11ea-8072-e85875a8a332.gif)

Actual (GitHub Writer):

![diff2](https://user-images.githubusercontent.com/566463/81179853-8530c680-8faa-11ea-8400-358d7e566037.gif)

Browser: Firefox 75 (Mac)
Extension version: 1.0.0

**Comment by fredck** [comment]
That's is supposed to work... it works for me.

It may be that your repo has something particular which makes the issues list to not load. If you're able to, can you check these points:

*   Do you have any console error?
*   Does it work for other kinds of mentions, like @ and : ?

Then, a bit more complicated debugging... can you put somewhere ([gist](http://gist.github.com/)?) the contents of the response for the xhr request made when using the **markdown editor** and typing # ? You should be able to see it coming in the "Network" panel of the dev tools in Firefox for the first time you type # after loading the page. The request start with `issue?...` and returns json data.

I can give you a step-by-step for the above, if you want.

Thanks!

**Comment by warpech** [comment]
I have the following errors in Firefox console:

> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

> mention-feed-callback-error: Could not obtain mention autocomplete feed. Read more: [https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-mention-feed-callback-error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-mention-feed-callback-error)

**Comment by fredck** [comment]
I believe the root of the problem is the same as in [#16](https://github.com/ckeditor/github-writer/issues/167)8\. Please follow my instructions there to see if we can figure out what is causing this issue in your installation.

**Comment by warpech** [comment]
Indeed, this reference was now made in Firefox: #168 

See my comment: https://github.com/ckeditor/github-writer/issues/168#issuecomment-625325459

**Comment by fredck** [comment]
Great! Thanks for checking this ;)

Have fun with GitHub Writer now!
