### ISSUE TITLE
Replace the Markdown editor when editing md files

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#171]
Reported by the community on one of FB groups.

I mean replacing editors like https://github.com/ckeditor/github-writer/edit/master/README.md.

I'm not sure if this features makes a lot of sense, taken the safe approach that GH Writer takes to already existing content, but perhaps it might work in some cases. Or perhaps we'll improve the "content compatibility" check in the  future and more content will be loadable to the editor.

**Comment by fredck** [comment]
This makes a lot of sense. Ofc, especially for md files, which are usually used for documentation where quick fixes are always welcome.

**Comment by Eccenux** [comment]
Maybe some option to opt-in would be nice.

So maybe something like:

1.  Do the content compatibility check.
2.  If the check fails do not load the editor.
3.  But provide a button to enable the editor.
4.  When button is clicked warn with a message like:  
    "This might brake some of your syntax. Be sure to check modifications before saving.  
      
    Are you sure you want to continue?"

Personally I would be fine if there are minor changes in the syntax of most of my MD files.

**Comment by fredck** [comment]
@Eccenux thanks for the suggestion... and, in fact, that's **exactly** the way GitHub Writer work right now.

For example, if you try to edit an existing comment (not created with GitHub Writer), the compatibility check is done and, if not compatible, the standard Markdown editor is displayed, with the "kebab" button to switch to rte (with the confirmation message).

So it looks like we're in the right road to make it right ;)

**Comment by CoreyVidal** [comment]
I have been on the hunt for something exactly like this. I do a lot of editing of README.md in-browser. Having a WYSIWYG markdown editor sounds like a no-brainer, but I just can't seem to find one. This would be greatly appreciated.
