### ISSUE TITLE
Strange things happen after typing more than 6 numbers in a row

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/github-writer#175]
I guess that after typing more than 6 numbers or rather from the range 0-9a-f, there's done a check if the text points to the specific commit hash in the repository. However, typing numbers quickly creates some text->link->text blinks, it's impossible to select the whole number/word from the right side and a strange data is stored to the session storage.

Typing 11111111 saves in the storage the following data:

```
 <text attribs="{&quot;autolink&quot;:{&quot;text&quot;:&quot;11111111&quot;,&quot;type&quot;:&quot;sha&quot;,&quot;enabled&quot;:false}}">11111111</text>
```

Shouldn't it be just `1111111` as it's still a text, not a hash?

**Comment by fredck** [comment]
Yes, that's the way autolinking works:

*    It assumes that things that match autolinks are really autolinks, in this way it gives an immediate feedback to the user without delay.
    *   This styles the autolink accordingly... in this case, as a hash.
*   Then, in case of GH stuff (hashes, people, issues) it makes a xhr request to check if that is really a valid GH reference.
    *   If true, it does nothing
    *   If false, it marks the autolink in the model with `enabled:false`, as you see in the data. This removes the style from the autolink.

We could try to improve this so maybe for hashes we do the opposite... first show them not styled and after GH confirmation we style them.

Hopefully this is not a very common use case.

**Comment by fredck** [comment]
The special behavior change for hashes has been introduced within ae1323c.
