### ISSUE TITLE
Add link to Chrome/Firefox extension pages in README

### ISSUE THREAD

**Issue by wwalc** [ckeditor/github-writer#176]
There is a chance that in some places, the link to the GitHub repository will be used to point to GitHub Writer. Therefore it may make sense to consider README as a starting place for both: developers interested in the source code but also for people just looking to use it.  
  
I'd add these two links in README in some separate section:

*   https://addons.mozilla.org/en-US/firefox/addon/github-writer/
*   https://chrome.google.com/webstore/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap

**Comment by fredck** [comment]
Good idea.

README amended with cb591ee.
