### ISSUE TITLE
Space+emoji after a link become a part of the link

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/github-writer#181]
### Reproduction steps:

1.  Paste a link.
2.  Add a space.
3.  Type `:ta` and accept the 🎉 emoji from the list with <kbd>Enter</kbd>.
4.  It looks like there is a link and an emoji after it.

![](https://user-images.githubusercontent.com/538321/81791401-fa4e4f80-9506-11ea-9803-ae0f742c032a.png)

5.  Submit the comment.

### Expected result:

The emoji is not a part of the link.

### Actual result:

The space and the emoji become a part of the link. The link points to https://ckeditor.com/blog/CKFinder-3.5.1.1-for-PHP-released/%C2%A0:tada

![](https://user-images.githubusercontent.com/538321/81791310-dee34480-9506-11ea-8667-5be2cda6cf62.png)

**Comment by fredck** [comment]
For some reason CKEditor is enforcing a `&nbsp;` between the link and the emoji. On top of that, GitHub doesn't treat that `&nbsp;` as space and connects everything as part of the link :disappointed:

**Comment by fredck** [comment]
Confirmed as a CKEditor limitation: ckeditor/ckeditor5#6807
