### ISSUE TITLE
Textarea not synced with GithubWriter prevents from updating issue in Markdown (nostalgia) mode.

### ISSUE THREAD

**Issue by jodator** [ckeditor/github-writer#185]
Steps:

1.  I had [some content](https://github.com/ckeditor/ckeditor5/issues/6822#issuecomment-628663455) created in markdown (sorry but multicursors + markdown are way better than any visual editor for some type of editing).
2.  Switch to WYSIWIG mode but cancel the switch after the warning message.
3.  Edit the markdown source.
4.  Save the edit.

Expected: I'm able to save edited content.

Actual: :crying\_cat\_face:

![](https://user-images.githubusercontent.com/247363/81946010-1fbe8480-95ff-11ea-8c76-4154c80a1504.png)

### Technical details:

*   version: `1.0.1`
*   browser: Firefox

**Comment by jodator** [comment]
What's more annoying - this is also reproducible in fallback mode (same content - use edit) and use <kbd>CTRL</kbd>+<kbd>B</kbd> (ps. no `<kbd>` support ;) ) to bold markdown text using GH UI.

same story :(

**Comment by fredck** [comment]
> ps.: manual edit is also blocked so I can't edit this content without disabling GH Writer 😿

Not sure what you meant by this case, but the provided fix should cover most of the missing use cases for misleading form locking.

I'm sorry it was annoying. But, as a side note, the good thing is that, despite the PITA, hopefully no data loss happened, which was the whole point of introducing the form locking feature.

**Comment by fredck** [comment]
> (ps. no `<kbd>` support ;) )

No sure what you meant to say, but are you talking about this?

![](https://user-images.githubusercontent.com/630060/82034017-e426c780-969d-11ea-8497-83953cfbc505.png)

Or even auto-formatting when typing something like `|Ctrl+B|`?

**Comment by jodator** [comment]
> No sure what you meant to say, but are you talking about this?

Oh... I've missed that. Sorry!

**Comment by jodator** [comment]
> I'm sorry it was annoying. But, as a side note, the good thing is that, despite the PITA, hopefully no data loss happened, which was the whole point of introducing the form locking feature.

Thanks, I will check that at the next occasion.

The content was not lost so that is a plus. The PITA was abut my edits have to be copied somewhere so I could disable the add-on, refresh the page and then edit the message again.
