### ISSUE TITLE
Long lines in code blocks stretch the editor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#199]
![](https://user-images.githubusercontent.com/156149/86218739-884acc00-bb81-11ea-82fb-28ec93641c63.png)

**Comment by Reinmar** [comment]
I had to zoom out to like 25% to show all that, so that's why some things look odd.

**Comment by Reinmar** [comment]
I had to zoom out to like 25% to show all that, so that's why some things look odd.

**Comment by Reinmar** [comment]
For reference, GitHub adds a horizontal scrollbar to code blocks.

**Comment by fredck** [comment]
I believe this has been changed on the GH styles recently as I think this was working previously. It should be a simple CSS fix.

**Comment by fredck** [comment]
Also, it seems to happen in comment fields only, not on new issue fields.
