### ISSUE TITLE
Avoid having vertical scrollbars

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#20]
The fact that GHRTE removes vertical scrollbars in most cases is one of the best thing about it. Unfortunately, sometimes the vertical scrollbar remains. 

![](https://user-images.githubusercontent.com/156149/71182701-db5cd180-2276-11ea-9507-46173deab764.png)

**Comment by Reinmar** [comment]
I don't feel that this is a showstopper. I use GHWriter every day and as you know half of my work is writing issues and comments and articles on GH. And yet – I use the toolbar once a week maybe. Usually, when I want to insert an image from a file (which is another issue that I've been reporting: #21). Of course, I'm a "power user", so I don't need to press buttons most of the time, but then we get to the next point...

Not every comment is that long to not fit in your viewport. Even I rarely write such a long ones. That's an edge case, in fact. By removing the scrollbar you'll improve the experience for 49% cases and slightly worsen for 2%, assuming that:

*   49% of comments go below the current 300px limit – THIS IS OK NOW
*   49% of comments go above 300px but below your viewport's height – THIS WILL BE IMPROVED
*   2% are longer than your viewport so you won't see the toolbar without scrolling a bit – THIS WILL BE SLIGHTLY PROBLEMATIC.

**Comment by fredck** [comment]
@Reinmar thanks again for your opinion. I know it is biased towards "go for it!" but I still can't agree that not seeing the toolbar is an ok thing **for everyone**.

Anyway, I see that you found a way to make it work for you by having custom styles. Thanks for sharing the solution - it may help others.

**Comment by fredck** [comment]
I've introduced a new feature that optimizes the use of the available viewport size, but without ignoring the rest of the form, like submit buttons and the title field. It still brings in the scrollbar but it should satisfy the requirements of this issue.

Please feel free to reopen the issue if the proposed solution will still not be sufficient. Thanks!
