### ISSUE TITLE
Tab key should not be hijacked by the heading feature

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/github-writer#208]
So, when I tab into the editor I often press <kbd>Tab</kbd> too many times and since [CKEditor 5 issue templates](https://github.com/ckeditor/ckeditor5/issues/new/choose) always start with a heading, I'm changing the level of that heading instead of moving out of the editor. That always confuses me (when it happens).

At the same time, I was never tempted to use <kbd>Tab</kbd> to change the heading level. I never found it intuitive. We're also changing the [autoformatting feature](https://github.com/ckeditor/ckeditor5/issues/6170) on CKE5 side to allow switching heading levels more easily. So, that'll make the Tab key even less necessary.

**Comment by fredck** [comment]
The tab feature on headers was introduced as an experimental feature. Its future is in fact in the hands of users' feedback. Thanks for being the first to let us know... hopefully others will leave their opinion here as well.

**Comment by mlewand** [comment]
For me the biggest issue was moving the focus out of the editor in case when you have the focus in a heading.

That being said there's exactly the same issue with list, which is also troubling me - but that's another issue.

**Comment by fredck** [comment]
So, the plugin that introduces this specific feature has been disabled. We may get back to this if anyone would ever shout out that they're missing it.

Thanks for the feedback!
