### ISSUE TITLE
Move cursor before suggestion code block

### ISSUE THREAD

**Issue by vokiel** [ckeditor/github-writer#214]
It seems to be impossible to move the cursor before the suggestion code block on a PR review page.

**Comment by fredck** [comment]
It is actually possible to do so. You need to start an empty line at the top of the code-block and type <kbd>Enter</kbd> on that line:

![](https://user-images.githubusercontent.com/630060/90628165-713d6780-e21d-11ea-817e-5623e1031640.gif)

Finally, a suggestion code-block is not different from normal code-blocks in comments or issues. So the same behavior happens in all cases.

This behavior is defined by CKEditor 5 itself, therefore, if you think that it needs improvements, I would point you to [open an issue in the ckeditor5 repo directly](https://github.com/ckeditor/ckeditor5/issues).
