### ISSUE TITLE
Weird case of todo list + link + parenthesis

### ISSUE THREAD

**Issue by jodator** [ckeditor/github-writer#219]
I was editing a link like this:

```markdown
* [ckeditor/ckeditor5#7307](https://github.com/ckeditor/ckeditor5/pull/7307) (foo bar)
```

by making it a todo-list. However on save I've got:

```markdown
* [ckeditor/ckeditor5#7307 (foo bar)](https://github.com/ckeditor/ckeditor5/pull/7307)
```

![](https://user-images.githubusercontent.com/247363/90137396-ddc7ea80-dd75-11ea-8a0f-498dfdfa4356.gif)

**Comment by fredck** [comment]
This seems to be ckeditor/ckeditor5#5779, which luckily will be fixed on the upcoming upgrade of CKEditor 5 in GitHub Writer.

**Comment by mateuszzagorski** [comment]
The issue has been fixed and is no longer replicable.
