### ISSUE TITLE
'mutate' is not an exported object from 'namespace:rlang'

### ISSUE THREAD

**Issue by Daniglia** [ckeditor/github-writer#231]
df.raw <- df.szrecs %>%
  filter(raw) %>%
  dplyr::select(sz.id = sz.id, sz.yr = sz.yr, ctry = disc.ct, 
         pcs = raw.pcs, wgt = raw.wgt, lo.cl = raw_l, up.cl = raw_u, grp = raw.grp) %>%
  rlang::mutate(grp = reorder(grp, new.order = c(1, 2, 3, 5, 4, 6)))

This is the code I am trying to run but I always get the same mistake
'mutate' is not an exported object from 'namespace:rlang'

I have already tried to re-start R and to re-install rlang with install.packages("rlang") but it did not work.

**Comment by ma2ciek** [comment]
Hi @Daniglia.

I'm aware that this is not a proper repository to report the issue as your problem is with the R lang, not with the Github Writer extension :)
