### ISSUE TITLE
Indented code blocks are not preserved

### ISSUE THREAD

**Issue by richb-ibm** [ckeditor/github-writer#234]
If I have a list with an indented code block like this:
* item 1
* item 2
  ```
  code
  ```
* item 3

it always gets converted back to
* item 1
* item 2
```
code
```
* item 3

So I don't know if this is a feature request or a bug since I don't think there is any way to produce an indented code block in github writer but I know I can produce it directly in markdown but next time I edit with github writer it will undo the indented code block even if I am not editing those indented code block lines.

**Comment by fredck** [comment]
This is a current limitation at this moment and has been reported already in #57.
