### ISSUE TITLE
Repository branch problem...

### ISSUE THREAD

**Issue by ShapeGroup** [ckeditor/github-writer#236]
Hi. I find myself connected as a contributor to your repository. Not only do I have a branch, but I can't even get away from it. Could you help me, risk of doing damage in deleting the branch?

It is strange, because there is no way to eliminate me by leaving the branch free... am i confusing?  
  
"/github.com/ShapeGroup/github-writer" ?? why do i have what ?

**Comment by fredck** [comment]
What you have in fact is a **fork** of this repository at https://github.com/ShapeGroup/github-writer (note that it's under the "ShapeGroup" organization, not "ckeditor"). It's hard to say how you created it but I assume you did that inadvertently.

You can delete you fork at the settings page of your fork, probably at https://github.com/ShapeGroup/github-writer/settings. This will not delete the original repository (the one here).
