### ISSUE TITLE
Incorrect integration with GitHub's dark mode

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/github-writer#238]
Currently GitHub Writer seems to completely ignore the new GitHub's dark mode, which causes the text field to be white with very low text contrast:

![GitHub Writer in dark mode: the textfield is white and the text in it is light gray.](https://user-images.githubusercontent.com/1078728/101700379-38035e80-3a7d-11eb-871c-07af91a7a4cc.png)

**Comment by trackwell-mike** [comment]
I've created a PR that _might_ solve this issue. Will wait for feedback from @fredck.

**Comment by trackwell-mike** [comment]
Until this issue is resolved, [here's my update as a Chrome Extension](https://share.getcloudapp.com/2Nu0zyy4) for anyone that wants to drop this in.

**Comment by singularityhacker** [comment]
Thank you, @trackwell-mike! Unfortunately, the download link from this cloud app thingy doesn't work. Opens a new tab momentarily then closes immediately. And it requires an email address submission :/ Any way you can share this via dropbox?
