### ISSUE TITLE
Drag / Drop .txt File Upload Fails on Chrome / Firefox

### ISSUE THREAD

**Issue by banagale** [ckeditor/github-writer#258]
I'm able to successfully drag / drop images using this plugin, but the only way I can drag / drop upload .txt files is if I change the editor to "Edit markdown" (nostalgia) mode.

The readme says, "It provides all the features available in the GitHub plain-text editor, including Markdown input." so I think the intent to support this is there, perhaps I'm doing something wrong.

I tried a clean install of the plugin using the method recommended in #168.

**Comment by fredck** [comment]
DUP of #242
