### ISSUE TITLE
Incompatible with new GitHub Issue Beta format

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [ckeditor/github-writer#259]
![](https://user-images.githubusercontent.com/50082450/116762593-28c88180-aa1b-11eb-8549-baf723aeafcb.gif)

Due to the addon, the input fields on the new GitHub Issues Beta format get treated like one, which breaks the issue template.

Tested on Firefox 88.0

if you want to test it out yourself, the issue template from above is located [here](https://github.com/flybywiresim/a32nx/issues/new?assignees=&labels=Bug&template=bug_report_beta.yaml&title=Title+goes+here...)

**Comment by fredck** [comment]
Making it work with the new Issue Template feature may be challenging and time consuming. As for now, to make it safe, I think the best we can do is disabling GHW if the feature is in use and leave the compatibility work for the future.
