### ISSUE TITLE
Long text hovers the 'commit changes area button'

### ISSUE THREAD

**Issue by ctwhome** [ckeditor/github-writer#266]
![](https://user-images.githubusercontent.com/4195550/129138360-8024f3a6-abb2-4e7a-81cf-0b6d71e1977b.png)

**Comment by ctwhome** [comment]
when the new release will be available in the chrome store, I still have the problem with the current version!

**Comment by Dumluregn** [comment]
Hi, if you are in a hurry, you can try to build your own GH Writer locally using this repo and load it in Chrome - see [https://github.com/ckeditor/github-writer/blob/master/dev/README.md](https://github.com/ckeditor/github-writer/blob/master/dev/README.md) for details.

**Comment by ctwhome** [comment]
It works as a cham! built locally and simply drag and drop to the chrome extensions page. Thank you for the fix!
