### ISSUE TITLE
The UI is falling apart after recent GH updates

### ISSUE THREAD

**Issue by oleq** [ckeditor/github-writer#270]
This happens to the link UI, tables UI, mentions, etc.

![](https://user-images.githubusercontent.com/1099479/136518128-c216d2b5-b8f4-4ddd-87ef-b710a8bc8cbe.png)

![](https://user-images.githubusercontent.com/1099479/136518391-3bfea55c-30fc-4d60-86d9-e7c9695ba4d2.png)

[1k+ people are using this extension](https://chrome.google.com/webstore/detail/github-writer/diilnnhpcdjhhkjcbdljaonhmhapadap). Maybe there's some easy way to address these issues?

**Comment by fredck** [comment]
> stop using `!important` when aligning the editor's design (CSS) to the Github page.

This is unfortunately not that simple. We don't have control on the building and loading order of some CSS that get into conflict. For example, many of the `!important` usage is to overcome the CKEditor reset styles themselves.
