### ISSUE TITLE
Balloon toolbars have uneven spacing

### ISSUE THREAD

**Issue by mlewand** [ckeditor/github-writer#309]
![image](https://user-images.githubusercontent.com/5353898/158137031-a7af7305-b6bc-470a-bfe6-17bcbe265671.png)

👆 note space on the right, and uneven vertical alignment.

The toolbar should have nice and even spaces all around. It's important that we don't introduce any regression in the main toolbar though as I assume it shares (a lot of) the styles.

**Comment by mateuszzagorski** [comment]
Resolved as a part of #308.
