### ISSUE TITLE
GitHub Writer partially loaded

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/github-writer#337]
## 📝 Provide detailed reproduction steps (if any)

It happened randomly, so there aren't really any.

### ✔️ Expected result

The GitHub Writer is fully and correctly loaded.

### ❌ Actual result

It's a weird mix of GH Writer and native editor's UIs – there is no "Preview" tab, only the "Write" one but the formatting buttons are from the native editor. Additionally, the text field contains raw Markdown. In the screencast below I type a sentence and then try to bold one of the words by pressing <kbd>Cmd</kbd> + <kbd>B</kbd> which results in the markdown for bold (`**text**`) being rendered:

https://user-images.githubusercontent.com/1078728/176314917-24db934a-75ef-4a39-a7d9-20ece6ba83cb.mov

## 📃 Other details

* Browser: Google Chrome 103.0.5060.53
* OS: macOS 12.4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
Might be connected to #285.

**Comment by Reinmar** [comment]
This is happening to me all the time recently. But Zenhub extension has exactly the same issue – it works on page reload, but not on navigation and I bet it's not a coincidence. 

Anyway, it's a critical issue right now.

**Comment by Comandeer** [comment]
It seems that the issue is connected with the navigation inside GH.

**Working scenarios**

1.  Refreshing the page.
2.  Opening the page in the new tab.

**Non-working scenario**

1.  Opening the repo, then navigating through issues and opening one of the issues. If done in one tab, the navigation is handled by GH and the page is not refreshed. And then the issue is visible.
