### ISSUE TITLE
Toolbar buttons tooltips not visible when editing comment.

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/github-writer#347]
## 📝 Provide detailed reproduction steps (if any)

1.  Edit any comment
2.  Hover over one of the buttons inside of the toolbar

![](https://user-images.githubusercontent.com/11699569/183406587-4fe6c6e2-1cd0-41e9-81f7-a46ca336089a.png)

### ✔️ Expected result

Tooltip is visible.

### ❌ Actual result

Tooltip is not visible.

### ❓ Possible solution

It looks like this is caused by the fix we've applied here https://github.com/ckeditor/github-writer/pull/326/files.

## 📃 Other details

*   Browser: …
*   OS: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
This still happens, but only when you try adding review to a PR.

**Comment by Dumluregn** [comment]
Thanks @FilipTokarski, I extracted it to ckeditor/github-writer#354.
