### ISSUE TITLE
Native CKE5 tooltips are broken after bumping CKE5 to 35.1.0

### ISSUE THREAD

**Issue by mlewand** [ckeditor/github-writer#365]
## 📝 Provide detailed reproduction steps (if any)

The native CKE5 tooltips doesn't look properly after bumping CKE5 to 35.1.0. Note that it seems to me that buttons in the main toolbar of GH Writer are using customized tooltips.

I noticed this while reviewing #364.

1.  Build GHWriter extension with CKE5 35.1.0.
2.  Insert an image to GHW instance.
3.  Focus the image.
4.  Hover the image alt text button.

### ✔️ Expected result

It should look consistent, here's how it looked before editor bump:

![](https://user-images.githubusercontent.com/5353898/191199092-e013ddc7-d97a-450e-94e5-3fbedf26b011.png)

### ❌ Actual result

![](https://user-images.githubusercontent.com/5353898/191197799-3202c799-c26a-4c9a-95ed-3d4efa38680c.png)

Same thing for table toolbar:

![](https://user-images.githubusercontent.com/5353898/191198425-eacc4139-8b09-4658-99db-53601a719f96.png)

In heading dropdown menu there's the same issue:

![](https://user-images.githubusercontent.com/5353898/191200417-3bb6bebb-867b-492f-b089-158fd8342738.png)

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: …
*   OS: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Done in #370.
