### ISSUE TITLE
Simplify tooltips - use CKE5 native tooltips in GH Writer

### ISSUE THREAD

**Issue by mlewand** [ckeditor/github-writer#366]
## 📝 Provide a description of the improvement

Currently we're using native GItHub's tooltips in some places and CKEditor 5's tooltips in other places.

Let's remove custom tooltip handling and rely on CKEditor 5's native tooltips.

Doing so will give following benefits:

*   Simplified code base.
*   Unified tooltip handling. We don't want to show more than 1 tooltip when one button is focused with keyboard and someone will hover other button with a mouse. Current custom implementation doesn't handle this properly.

### Examples

Examples of GitHub's native tooltips include main toolbar and buttons in the "More options..." menu:

![](https://user-images.githubusercontent.com/5353898/191208936-99ba8523-9700-422d-8ccd-bc8712916c5f.png)

For example, CKE5 native tooltips are used in balloon toolbars and of heading buttons:

![](https://user-images.githubusercontent.com/5353898/191208731-b1056608-54ae-4008-8ecd-a0c5b225038c.png)

## 📃 Other details

*   Browser: Any
*   OS: Any

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Dumluregn** [comment]
Done in #370.
