### ISSUE TITLE
ChromeBook / ChromeOS

### ISSUE THREAD

**Issue by franz-ms-muc** [ckeditor/github-writer#372]
Hi, 

using your Chrome Plugin on a ChromeBook on ChromeOS seems to have issues. 
Editing not working. 
but the Plugin is shown, Toolbar is shown.

**Comment by mateuszzagorski** [comment]
Hi @franz-ms-muc we've created an issue to aggregate all the scenarios where GitHub Writer does not load correctly -> https://github.com/ckeditor/github-writer/issues/357. 
Please provide us with more details regarding this issue in there (detailed steps to reproduce, os/browser details, screens/video etc. ).
