### ISSUE TITLE
Focus and selection are moved to the above widget/paragraph when the Heading or Code buttons are pressed

### ISSUE THREAD

**Issue by dufipl** [ckeditor/github-writer#380]
## 📝 Provide detailed reproduction steps (if any)

1. Build GH Writer on the `ghw/epic/367-version-3510-bump` branch 
2. Insert an image and paragraph of text below.
3. Select the text and press the Heading button or the Code button on the toolbar

### ✔️ Expected result
Selection and focus remain on the text:
![focus heading GH writer expected](https://user-images.githubusercontent.com/32898551/194283213-db727194-368e-40c3-bcec-8d5fb075d4fa.gif)

### ❌ Actual result
Focus and selection are moved to the widget above: 
![focus heading GH writer actual](https://user-images.githubusercontent.com/32898551/194283326-1a882fdf-b34e-41a1-bed1-644c8514e798.gif)

### Additional information

**It is a regression from the last release.** 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
First thing that I see is that the focus doesn't go back to the editing view once button's _face_ is activated.

It might be that fixing it (making sure that the editable gets activated after pressing the button, as other buttons are) will solve the issue.

**Comment by mateuszzagorski** [comment]
When we'll bump the editor to version "^35.2.0" this issue will be resolved as there are some changes related to the toolbar focus behavior that we need.

**Comment by mlewand** [comment]
@mateuszzagorski can you verify this and close the issue if it is indeed fixed?

**Comment by mateuszzagorski** [comment]
After upgrading the editor version to `35.2.1` the behavior was still imperfect - so I've created a PR that should resolve all remaining issues.

**Comment by mlewand** [comment]
Fixed with https://github.com/ckeditor/github-writer/pull/404#pullrequestreview-1151030373
