### ISSUE TITLE
Integrate CKEditor 5 v35.2.x

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/github-writer#388]
Similarly to the recent `35.1.0` bump we've noticed there are some regressions/issues that should be fixed before we can merge the new CKE5 version.

So let's track this upgrade under this epic and make an epic branch for all the related fixes/improvements.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
The bump has been merged.
