### ISSUE TITLE
Add table grid needs styling update

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/github-writer#389]
## 📝 Provide detailed reproduction steps (if any)

1.  After bumping the editor to the latest version ("^35.2.0") build GH Writer.
2.  Try to add a new table

### ✔️ Expected result

![image](https://user-images.githubusercontent.com/11699569/195015369-8c190d93-613a-42ee-a83b-5f457c5c6930.png)

### ❌ Actual result

https://user-images.githubusercontent.com/11699569/195015955-1f633422-ac24-4eb2-80c0-b72327902d87.mov

### ❓ Possible solution

For the dark theme both the `.ck-insert-table-dropdown-grid-box` and `.ck-insert-table-dropdown__label` classes styles have to be updated.

## 📃 Other details

It is vital to check other themes (at least `single theme` light/dark default as well as the `Sync with system` theme mode)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mmotyczynska** [comment]
Might be a result of changing table grid items to ButtonView instances ckeditor/ckeditor5#12439.
