### ISSUE TITLE
Fix CSS for tooltips for GitHub "Sync with system" theme

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/github-writer#390]
## 📝 Provide detailed reproduction steps (if any)

1.  Switch GitHub theme to `Sync with system`.
2.  Hover over any button in the toolbar.

### ✔️ Expected result

The text and background colors are different and you can read its content.

![](https://user-images.githubusercontent.com/95343030/195057998-3b2c622a-d673-4820-aa8c-5e899e52c891.png)

### ❌ Actual result

The text and background colors are the same and you cannot read its content.

![](https://user-images.githubusercontent.com/95343030/194914930-7f4eb38a-e3ba-4f07-bd40-9e15b8b52dae.png)

### ❓ Possible solution

We should add some more CSS selectors for the `Sync with system` theme. For now we already have selectors for `light` theme `html[data-color-mode="light"]` in `panel.css` file and probably we just have to create a similar ones for `html[data-color-mode="auto"]`.

## 📃 Other details

*   Browser: …
*   OS: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
After bumping used editor version to 35.2.1 the problem within the main toolbar seems to be fixed.

However it does not fix the behavior for table/image balloon toolbar, and when hovering over the the opened heading dropdown buttons.
