### ISSUE TITLE
Insert image not working on chrome

### ISSUE THREAD

**Issue by mateuszzagorski** [ckeditor/github-writer#401]
## 📝 Provide detailed reproduction steps (if any)

1.  Click `Insert image` button from the main toolbar

### ✔️ Expected result

You can select an image to be inserted from your file manager.

### ❌ Actual result

Nothing happens.

## 📃 Other details

It is still possible to add image with d&d as it should be.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
It does not look like reproducing anymore, so closing. :)
