### ISSUE TITLE
GitHub Write Feature Request - Add support for Github project drafts

### ISSUE THREAD

**Issue by dszczepaniak-cksource** [ckeditor/github-writer#419]
## 📝 Provide a description of the new feature

Originally the feature request was sent to browser-extensions@cksource.com by frode@keenious.com:

```
Hi, 

Could you please add support for the new GitHub projects? Would love to use GitHub writer there as well!

This is what I am talking about:
```
![image](https://user-images.githubusercontent.com/93583958/201855413-069507b0-0ec5-4cbd-b2d4-07a70412498f.png)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This feature has been added in #386 - I'm merging it there.
