### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by qertony** [ckeditor/github-writer#437]
`##` 📝 Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
Github issues do work 😉 👌
