### ISSUE TITLE
[opinionated] Prefer emitting `-` over `*` for unordered list markup

### ISSUE THREAD

**Issue by zm-cttae** [ckeditor/github-writer#438]
### Problem statement

- **As a:** open-source developer writing issues on GitHub
- **I want to:** use the same modern Markdown settings as my organisation or repository
- **So that:** I can onboard and share comments consistent to a [Markdown style guide](https://github.com/svengreb/styleguide-markdown).

### Proposed solution

Adopt the GitHub and [CommonMark](https://commonmark.org/help/) conventions of Markdown formatting punctuation/operators.
In an ideal world the editor would emit `-` for unordered lists.
Other settings are `{ headingStyle: 'atx', bulletListMarker: '-', emDelimiter: '*', br: '\n' }`
Technically, this is a breaking change to the project and may not be worth the dev time.

### Describe alternatives you've considered

A setting is provided so that users can select their preference.
This is more complex and requires a big growth to the the codebase.
Honestly why would someone intentionally want to use `*` and setext headings like `## Header 2 ##`.
It seems secondary to having some saner defaults.

[vsctmls-issues]: https://github.com/vsce-toolroom/vscode-textmate-languageservice/issues?q=is%3Aopen+sort%3Aupdated-desc

---

> If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by meche-gh** [comment]
This has nothing to do with github writer - it's a upstream issue in `turndown`. mixmark-io/turndown#424

**Comment by zm-cttae** [comment]
Reopening in case the upstream PR is rejected
