### ISSUE TITLE
Review can't be submitted with Writer

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/github-writer#443]
## 📝 Provide detailed reproduction steps (if any)

1.  Open a PR.
2.  Try to submit review with GH Writer loaded.

### ✔️ Expected result

Review is submitted.

### ❌ Actual result

There's a console error and nothing happens:

![](https://user-images.githubusercontent.com/10883184/237046374-92b24043-7ac4-44e4-a515-9579c3d615f7.png)

### ❓ Possible solution

Probably GH changes sth in its DOM structure.

## 📃 Other details

*   Browser: …
*   OS: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mrm-david** [comment]
Unless I disable the extension, I can't submit the review. Same error in the console.

**Comment by Dumluregn** [comment]
An emergency workaround is switching to "Nostalgia" mode just to submit the review:

![](https://github.com/ckeditor/github-writer/assets/10883184/cd12aad1-b9b9-4398-939d-ed26542e4ded)
