### ISSUE TITLE
GitHub Writer error: ("markdown") not found error when trying to edit issue or comment

### ISSUE THREAD

**Issue by dufipl** [ckeditor/github-writer#453]
## 📝 Provide detailed reproduction steps (if any)
GitHub Writer error: ("markdown") not found error when trying to edit issue or comment
1. Open any issue
2. Press on the 3 dots in the upper right corner and then press anywhere else

### ✔️ Expected result

No errors in the console.

### ❌ Actual result

https://github.com/ckeditor/github-writer/assets/32898551/cd6aa657-5a77-4643-a87f-1861d3dd2f9d

Error in the console:
```
Uncaught (in promise) Error: GitHub Writer error: ("markdown") not found. This page doesn't seem to be compatible with this application anymore. Upgrade to the latest version of the browser extension.
    at github-writer.js:6:882
    at Array.forEach (<anonymous>)
    at c (github-writer.js:6:840)
    at github-writer.js:6:939
    at Array.forEach (<anonymous>)
    at c (github-writer.js:6:840)
    at new yk (github-writer.js:5094:177)
    at new vk (github-writer.js:5103:4)
    at vk.createEditor (github-writer.js:5082:483)
    at window.requestIdleCallback.window.requestIdleCallback.timeout (github-writer.js:5082:179)
```

## 📃 Other details

* Browser: Both Chrome and Firefox
* OS: Mac

Might be connected with: #452 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
This actually might be similar to #443
