### ISSUE TITLE
Extension does not load (only shows markdown editor) for Issues & Wiki in both Chrome & Firefox

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [ckeditor/github-writer#470]
## 📝 Provide detailed reproduction steps (if any)

I installed GitHub Writer v1.10.2 (latest) to both Chrome and Firefox. It would not show a WYSIWYG editor when creating a new issue or editing a wiki page. I only get the default markdown editor. :(

In the Chrome developer console I get this error message:  
`github-writer.js:3148 Error: GitHub Writer error: ("panelsContainer") not found. This page doesn't seem to be compatible with this application anymore. Upgrade to the latest version of the browser extension.`  
 `at github-writer.js:6:882`  
 `at Array.forEach (<anonymous>)`  
 `at c (github-writer.js:6:840)`  
 `at new yk (github-writer.js:5094:177)`  
 `at new Ck.repo_issues.features (github-writer.js:5143:1)`  
 `at Ck.repo_issues.features.createEditor (github-writer.js:5082:483)`  
 `at Ck.repo_issues.features.run (github-writer.js:5143:124)`  
 `at Object.run (github-writer.js:5156:2011)`  
 `at github-writer.js:11:92`

## 📃 Other details

*   Browser: Chrome & Firefox
*   OS: Windows 11

I restarted both browsers to no avail.

In Firefox the only other extension I have installed is Adblock Plus, and I disabled it for GitHub and reloaded the pages. I also have no other tabs open in FF.

In Chrome I disabled potentially conflicting plugins: AdBlock, uBlock Origin, DarkReader.

Javascript is enabled for both browsers and no restrictive security settings are in place (should be default).

Of course I was signed in to GitHub during the tests.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by CodeSmile-0000011110110111** [comment]
Guess what? I was editing my issue post after submitting it, and once (!) the visual editor did load. I saved and tried editing again but the editor was back to normal (default markdown).

**Comment by Drumstix42** [comment]
I don't know this extension too well yet, but upon inspecting the Github DOM, it looks like maybe some class names changed in the HTML. Looks like `previewable-comment-form` is now `js-previewable-comment-form`. I think an extension update will be needed to address this.

**Comment by Witoso** [comment]
Looks like some changes to the [GitHub's comment field were released](https://github.blog/changelog/2023-10-31-the-comment-box-becomes-more-consistent-and-accessible/), and we need to fix it on our side. Thanks for the issue!
