### ISSUE TITLE
Broken appearance

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/github-writer#480]
## 📝 Provide detailed reproduction steps (if any)

1. Open any GitHub issue and scroll to the comment editor.

### ✔️ Expected result

GitHub writer has a readable, visible UI.

### ❌ Actual result

UI is nearly invisible and the additional toolbar does not have any background. The issue is more prominent in any of the GH dark themes:
![Screenshot 2024-04-03 at 12 46 18](https://github.com/ckeditor/github-writer/assets/1078728/ed188eb2-7715-465b-a008-f7fbabfe3573)

### ❓ Possible solution

Probably styles for GH Writer should be updated.

## 📃 Other details

* Browser: Google Chrome 123.0.6312.87
* OS: macOS 14.4.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by illia-stv** [comment]
I noticed in light theme it's also doesn't look very nice in my opinion, are we okay with that transparent background?

![](https://github.com/ckeditor/github-writer/assets/47000454/5ca54ab5-9d25-4bbb-84c2-86ece484bb7e)

What do you think about inheriting background (not transparent) like this?  
 

![](https://github.com/ckeditor/github-writer/assets/47000454/77f13691-c7f3-49d4-a8c1-6fb059efa7c2)

**Comment by Witoso** [comment]
Yes, this is the same issue. If `inherit` solves it, we are good to go. The question is about icon colors, I cannot check it how it worked in previous version, but I'm almost 100% sure that the colors were reversed.
